apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    
    nginx.org/ssl-services: smart-edilek-api
  name: edilek-api-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: dev-api.edilek.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: smart-edilek-api
            port:
              number: 8443
  tls:
  - hosts:
    - dev-api.edilek.com
    secretName: edilek-wildcard-cert-prod