apiVersion: k8s.nginx.org/v1
kind: TransportServer
metadata:
  name: debug-smart-edilek-api
  namespace: e-dilek-dev
spec:
  listener:
    # Global Configuraiton >> nginx-configuration >> debug-{n}-listener
    # nginx Namespace >> nginx Deployment >> debug-{n}-port >> port should be modified
    name: debug-03-listener
    protocol: TCP 
  upstreams:
    - name: debug-03-upstream
      service: smart-edilek-api
      port: 5007
  action:
    pass: debug-03-upstream