apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-edilek-api
  labels:
    app: smart-edilek-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: smart-edilek-api
  template:
    metadata:
      labels:
        app: smart-edilek-api
    spec:
      containers:
      - name: smart-edilek-api
        image: docker-r.nexus.s3t.co/smart/edilek:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: httpsport
            containerPort: 8443
            protocol: TCP
        resources:
          requests:
            memory: "512Mi"  # Minimum RAM ihtiyacı
            cpu: "250m"      # Minimum CPU ihtiyacı
          limits:
            memory: "1024Mi" # Maksimum RAM
            cpu: "500m"      # Maksimum CPU
        env:
          - name: DATASOURCE_URL
            valueFrom: 
              secretKeyRef:
                name: edilek-configuration-secret
                key: smart-database-url
          - name: DATASOURCE_USERNAME
            valueFrom: 
              secretKeyRef:
                name: edilek-configuration-secret
                key: smart-database-username
          - name: DATASOURCE_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: edilek-configuration-secret
                key: smart-database-password
          - name: CERTIFICATE_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: edilek-configuration-secret
                key: smart-certificate-password
          - name: KEYCLOAK_AUTH_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: edilek-configmap
                key: keycloak-auth-server-url
          - name: KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                name: edilek-configmap
                key: keycloak-realm
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: edilek-configmap
                key: keycloak-client-id 
          - name: NOWPAYMENTS_IPN_SECRET
            valueFrom:
              configMapKeyRef:
                name: edilek-configmap
                key: nowpayment-ipn-key
          - name: OPENAI_API_KEY
            valueFrom:
              configMapKeyRef:
                name: edilek-configmap
                key: openai-api-key
        volumeMounts:
          - name: my-certificate-volume
            mountPath: "/etc/certs"
      volumes:
        - name: my-certificate-volume
          secret:
            secretName: edilek-wildcard-cert-prod-p12
      imagePullSecrets:
        - name: nexus-s3t-co-docker-config