apiVersion: v1
kind: Secret
metadata:
  name: edilek-configuration-secret
type: Opaque
data:
  smart-certificate-password: xxxxxx
  smart-database-username: xxxxxx
  smart-database-password: xxxxxx
  smart-database-url: xxxxxx