apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.org/ssl-services: smart-edilek-api
  name: edilek-api-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: api.edilek.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: smart-edilek-api
            port:
              number: 8443
  tls:
  - hosts:
    - api.edilek.com
    secretName: edilek-wildcard-cert-prod